### ISSUE TITLE
Wrong hostname displayed in the lock screen

### ISSUE THREAD

**Issue by Crash--** [cozy/cozy-keys-browser#83]
I don't know how [webVaultHostname](https://github.com/bitwarden/jslib/blob/b3d1e9d233aa7ed235d6ec0b26cdba41afa065ae/src/angular/components/lock.component.ts#L49) can be empty in some case, but here is an exemple of what I get sometimes 

<img width="364" alt="Capture d’écran 2020-04-10 à 09 03 14" src="https://user-images.githubusercontent.com/1107936/78971049-fa73bd80-7b0a-11ea-82eb-2e95cfed42dc.png">

see https://github.com/cozy/cozy-keys-browser/pull/82

**Comment by zatteo** [comment]
Working now
